"""initial tables

Revision ID: cc6cce0469c5
Revises: 
Create Date: 2026-05-26 12:41:11.125197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6cce0469c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('id_image_url', sa.String(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('location_city', sa.String(length=50), nullable=True),
    sa.Column('location_area', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), nullable=True),
    sa.Column('active_jobs_count', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number')
    )
    op.create_index(op.f('ix_taskers_id'), 'taskers', ['id'], unique=False)
    op.create_index(op.f('ix_taskers_phone_number'), 'taskers', ['phone_number'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('tasker_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('tasker_amount', sa.Integer(), nullable=False),
    sa.Column('platform_commission', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ESCROWED', 'RELEASED', 'REFUNDED', 'FAILED', name='transactionstatus'), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('mpesa_phone_number', sa.String(length=15), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('escrowed_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_job_id'), 'transactions', ['job_id'], unique=False)
    op.create_index(op.f('ix_transactions_recruiter_id'), 'transactions', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_transactions_tasker_id'), 'transactions', ['tasker_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasker_id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Integer(), nullable=True),
    sa.Column('pending_balance', sa.Integer(), nullable=True),
    sa.Column('pending_withdrawals', sa.Integer(), nullable=True),
    sa.Column('total_earned', sa.Integer(), nullable=True),
    sa.Column('total_withdrawn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tasker_id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_transactions_tasker_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_recruiter_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_job_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_taskers_phone_number'), table_name='taskers')
    op.drop_index(op.f('ix_taskers_id'), table_name='taskers')
    op.drop_table('taskers')
    # ### end Alembic commands ###
